export const TeamInventory = [
    {
        TeamFname: "CINCINNATI",
        TeamLname: "BENGALS",
        TeamPic: "/bengals.png",
        TeamRating: 78,
        TeamOFF: 79,
        TeamDEF: 83,
        Position1: "DT",
        Player1Fname: "GENO",
        Player1Lname: "ATKINS",
        Player1OVR: 94,
        Position2: "WR",
        Player2Fname: "A.J.",
        Player2Lname: "GREEN",
        Player2OVR: 91,
        Position3: "TE",
        Player3Fname: "TYLER",
        Player3Lname: "ELFERT",
        Player3OVR: 89
    },
    {
        TeamFname: "TAMPA BAY",
        TeamLname: "BUCCANEERS",
        TeamPic: "/BUCCANEERS.png",
        TeamRating: 79,
        TeamOFF: 85,
        TeamDEF: 79,
        Position1: "ROLB",
        Player1Fname: "LAVONTE",
        Player1Lname: "DAVID",
        Player1OVR: 95,
        Position2: "WR",
        Player2Fname: "MIKE",
        Player2Lname: "EVANS",
        Player2OVR: 90,
        Position3: "LG",
        Player3Fname: "ALI",
        Player3Lname: "MARPET",
        Player3OVR: 88
    },
    {
        TeamFname: "ARIZONA",
        TeamLname: "CARDINALS",
        TeamPic: "/CARDINALS.jpeg",
        TeamRating: 73,
        TeamOFF: 73,
        TeamDEF: 79,
        Position1: "CB",
        Player1Fname: "PATRICK",
        Player1Lname: "PETERSON",
        Player1OVR: 92,
        Position2: "HB",
        Player2Fname: "DAVID",
        Player2Lname: "JOHNSON",
        Player2OVR: 87,
        Position3: "WR",
        Player3Fname: "LARRY",
        Player3Lname: "FITZGERALD",
        Player3OVR: 85
    },
    {
        TeamFname: "NEW YORK",
        TeamLname: "JETS",
        TeamPic: "/JETS.png",
        TeamRating: 77,
        TeamOFF: 77,
        TeamDEF: 81,
        Position1: "SS",
        Player1Fname: "JAMAL",
        Player1Lname: "ADAMS",
        Player1OVR: 89,
        Position2: "LE",
        Player2Fname: "LEONARD",
        Player2Lname: "WILLIAMS",
        Player2OVR: 87,
        Position3: "MLB",
        Player3Fname: "AVERY",
        Player3Lname: "WILLIAMSON",
        Player3OVR: 84
    },
    {
        TeamFname: "OAKLAND",
        TeamLname: "RAIDERS",
        TeamPic: "/RAIDERS.png",
        TeamRating: 76,
        TeamOFF: 81,
        TeamDEF: 75,
        Position1: "C",
        Player1Fname: "RODNEY",
        Player1Lname: "HUDSON",
        Player1OVR: 94,
        Position2: "HB",
        Player2Fname: "MARSHAWN",
        Player2Lname: "LYNCH",
        Player2OVR: 88,
        Position3: "TE",
        Player3Fname: "JARED",
        Player3Lname: "COOK",
        Player3OVR: 88
    },
    {
        TeamFname: "NEW YORK",
        TeamLname: "GIANTS",
        TeamPic: "/GIANTS.jpeg",
        TeamRating: 73,
        TeamOFF: 77,
        TeamDEF: 73,
        Position1: "WR",
        Player1Fname: "ODELL",
        Player1Lname: "BECKHAM JR",
        Player1OVR: 96,
        Position2: "HB",
        Player2Fname: "SAQUON",
        Player2Lname: "BARKLEY",
        Player2OVR: 88,
        Position3: "TE",
        Player3Fname: "EVEN",
        Player3Lname: "ENGRAM",
        Player3OVR: 85
    },
    {
        TeamFname: "CLEVELAND",
        TeamLname: "BROWNS",
        TeamPic: "/BROWNS.png",
        TeamRating: 80,
        TeamOFF: 83,
        TeamDEF: 83,
        Position1: "RE",
        Player1Fname: "MYLES",
        Player1Lname: "GARRETT",
        Player1OVR: 93,
        Position2: "RG",
        Player2Fname: "KEVIN",
        Player2Lname: "ZEITLER",
        Player2OVR: 89,
        Position3: "LG",
        Player3Fname: "JOEL",
        Player3Lname: "BITONIO",
        Player3OVR: 88
    },
    {
        TeamFname: "MIAMI",
        TeamLname: "DOLPHINS",
        TeamPic: "/DOLPHINS.png",
        TeamRating: 77,
        TeamOFF: 81,
        TeamDEF: 79,
        Position1: "LE",
        Player1Fname: "CAMERON",
        Player1Lname: "WAKE",
        Player1OVR: 89,
        Position2: "LE",
        Player2Fname: "WILLIAM",
        Player2Lname: "HAYES",
        Player2OVR: 86,
        Position3: "WR",
        Player3Fname: "KENNY",
        Player3Lname: "STILLS",
        Player3OVR: 85
    },
    {
        TeamFname: "DETROIT",
        TeamLname: "LIONS",
        TeamPic: "/LIONS.png",
        TeamRating: 76,
        TeamOFF: 81,
        TeamDEF: 77,
        Position1: "DT",
        Player1Fname: "DAMON",
        Player1Lname: "HARRISON SR",
        Player1OVR: 94,
        Position2: "CB",
        Player2Fname: "DARIUS",
        Player2Lname: "SLAY JR",
        Player2OVR: 88,
        Position3: "WR",
        Player3Fname: "MARVIN",
        Player3Lname: "JONES JR",
        Player3OVR: 87
    },
    {
        TeamFname: "TENNESSEE",
        TeamLname: "TITANS",
        TeamPic: "/TITANS.png",
        TeamRating: 81,
        TeamOFF: 85,
        TeamDEF: 83,
        Position1: "TE",
        Player1Fname: "DELANIE",
        Player1Lname: "WALKER",
        Player1OVR: 92,
        Position2: "RE",
        Player2Fname: "JURRELL",
        Player2Lname: "CASEY",
        Player2OVR: 89,
        Position3: "FS",
        Player3Fname: "KEVIN",
        Player3Lname: "BYARD",
        Player3OVR: 88
    },
    {
        TeamFname: "ATLANTA",
        TeamLname: "FALCONS",
        TeamPic: "/FALCONS.png",
        TeamRating: 84,
        TeamOFF: 87,
        TeamDEF: 85,
        Position1: "WR",
        Player1Fname: "JULIO",
        Player1Lname: "JONES",
        Player1OVR: 98,
        Position2: "MLB",
        Player2Fname: "DEION",
        Player2Lname: "JONES",
        Player2OVR: 91,
        Position3: "CB",
        Player3Fname: "DESMOND",
        Player3Lname: "TRUFANT",
        Player3OVR: 90
    },
    {
        TeamFname: "CAROLINA",
        TeamLname: "PANTHERS",
        TeamPic: "/PANTHERS.jpeg",
        TeamRating: 82,
        TeamOFF: 81,
        TeamDEF: 85,
        Position1: "MLB",
        Player1Fname: "LUKE",
        Player1Lname: "KUECHLY",
        Player1OVR: 97,
        Position2: "HB",
        Player2Fname: "CHRISTIAN",
        Player2Lname: "MCCAFFREY",
        Player2OVR: 92,
        Position3: "TE",
        Player3Fname: "GREG",
        Player3Lname: "OLSON",
        Player3OVR: 90
    },
    {
        TeamFname: "SAN FRANCISCO",
        TeamLname: "49ERS",
        TeamPic: "/49ERS.jpeg",
        TeamRating: 78,
        TeamOFF: 85,
        TeamDEF: 75,
        Position1: "CD",
        Player1Fname: "RICHARD",
        Player1Lname: "SHERMAN",
        Player1OVR: 93,
        Position2: "LT",
        Player2Fname: "JOE",
        Player2Lname: "STALEY",
        Player2OVR: 89,
        Position3: "TE",
        Player3Fname: "GEORGE",
        Player3Lname: "KITTLE",
        Player3OVR: 89
    },
    {
        TeamFname: "MINNESOTA",
        TeamLname: "VIKINGS",
        TeamPic: "/VIKINGS.jpeg",
        TeamRating: 81,
        TeamOFF: 81,
        TeamDEF: 87,
        Position1: "WR",
        Player1Fname: "ADAM",
        Player1Lname: "THIELEN",
        Player1OVR: 94,
        Position2: "SS",
        Player2Fname: "HARRISON",
        Player2Lname: "SMITH",
        Player2OVR: 94,
        Position3: "WR",
        Player3Fname: "STEFON",
        Player3Lname: "DIGGS",
        Player3OVR: 92
    },
    {
        TeamFname: "DENVER",
        TeamLname: "BRONCOS",
        TeamPic: "/BRONCOS.png",
        TeamRating: 78,
        TeamOFF: 79,
        TeamDEF: 83,
        Position1: "LOLB",
        Player1Fname: "VON",
        Player1Lname: "MILLER",
        Player1OVR: 98,
        Position2: "CB",
        Player2Fname: "CHRIS",
        Player2Lname: "HARRIS JR",
        Player2OVR: 89,
        Position3: "WR",
        Player3Fname: "EMMANUEL",
        Player3Lname: "SANDERS",
        Player3OVR: 89
    },
    {
        TeamFname: "GREEN BAY",
        TeamLname: "PACKERS",
        TeamPic: "/PACKERS.png",
        TeamRating: 81,
        TeamOFF: 85,
        TeamDEF: 81,
        Position1: "LT",
        Player1Fname: "DAVID",
        Player1Lname: "BAKHTIARI",
        Player1OVR: 98,
        Position2: "QB",
        Player2Fname: "AARON",
        Player2Lname: "RODGERS",
        Player2OVR: 93,
        Position3: "WR",
        Player3Fname: "DAVANTE",
        Player3Lname: "ADAMS",
        Player3OVR: 91
    },
    {
        TeamFname: "BALTIMORE",
        TeamLname: "RAVENS",
        TeamPic: "/RAVENS.png",
        TeamRating: 82,
        TeamOFF: 83,
        TeamDEF: 83,
        Position1: "RG",
        Player1Fname: "MARSHAL",
        Player1Lname: "YANDA",
        Player1OVR: 93,
        Position2: "LE",
        Player2Fname: "BRANDON",
        Player2Lname: "WILLIAMS",
        Player2OVR: 88,
        Position3: "DT",
        Player3Fname: "MICHEAL",
        Player3Lname: "PIERCE",
        Player3OVR: 88
    },
    {
        TeamFname: "Kansas City",
        TeamLname: "Cheifs",
        TeamPic: "/KC.svg",
        TeamRating: 84,
        TeamOFF: 87,
        TeamDEF: 83,
        Position1: "TE",
        Player1Fname: "TRAVIS",
        Player1Lname: "KELCE",
        Player1OVR: 96,
        Position2: "SS",
        Player2Fname: "ERIC",
        Player2Lname: "BERRY",
        Player2OVR: 95,
        Position3: "WR",
        Player3Fname: "TYREEK",
        Player3Lname: "HILL",
        Player3OVR: 93
    },
    {
        TeamFname: "INDIANAPOLIS",
        TeamLname: "COLTS",
        TeamPic: "/COLTS.png",
        TeamRating: 76,
        TeamOFF: 83,
        TeamDEF: 75,
        Position1: "WR",
        Player1Fname: "T.Y.",
        Player1Lname: "HILTON",
        Player1OVR: 90,
        Position2: "LE",
        Player2Fname: "JABAAL",
        Player2Lname: "SHEARD",
        Player2OVR: 87,
        Position3: "QB",
        Player3Fname: "ANDREW",
        Player3Lname: "LUCK",
        Player3OVR: 87
    },
    {
        TeamFname: "SEATTLE",
        TeamLname: "SEAHAWKS",
        TeamPic: "/SEAHAWKS.jpeg",
        TeamRating: 82,
        TeamOFF: 81,
        TeamDEF: 85,
        Position1: "MLB",
        Player1Fname: "BOBBY",
        Player1Lname: "WAGNER",
        Player1OVR: 99,
        Position2: "FS",
        Player2Fname: "EARL",
        Player2Lname: "THOMAS III",
        Player2OVR: 96,
        Position3: "QB",
        Player3Fname: "RUSSELL",
        Player3Lname: "WILSON",
        Player3OVR: 90
    },
    {
        TeamFname: "CHICAGO",
        TeamLname: "BEARS",
        TeamPic: "/BEARS.png",
        TeamRating: 82,
        TeamOFF: 81,
        TeamDEF: 89,
        Position1: "LOLB",
        Player1Fname: "KHALIL",
        Player1Lname: "MACK",
        Player1OVR: 99,
        Position2: "LE",
        Player2Fname: "AKIEM",
        Player2Lname: "HICKS",
        Player2OVR: 90,
        Position3: "TE",
        Player3Fname: "TREY",
        Player3Lname: "BURTON",
        Player3OVR: 88
    },
    {
        TeamFname: "HOUSTON",
        TeamLname: "TEXANS",
        TeamPic: "/TEXANS.jpeg",
        TeamRating: 81,
        TeamOFF: 81,
        TeamDEF: 87,
        Position1: "LE",
        Player1Fname: "J.J.",
        Player1Lname: "WATT",
        Player1OVR: 98,
        Position2: "WR",
        Player2Fname: "DEANDRE",
        Player2Lname: "HOPKINS",
        Player2OVR: 96,
        Position3: "SS",
        Player3Fname: "TYRANN",
        Player3Lname: "MATHIEU",
        Player3OVR: 91
    },
    {
        TeamFname: "JACKSONVILLE",
        TeamLname: "JAGUARS",
        TeamPic: "/JAGUARS.jpeg",
        TeamRating: 83,
        TeamOFF: 81,
        TeamDEF: 91,
        Position1: "CB",
        Player1Fname: "JALEN",
        Player1Lname: "RAMSEY",
        Player1OVR: 93,
        Position2: "LE",
        Player2Fname: "CALAIS",
        Player2Lname: "CAMPBELL",
        Player2OVR: 93,
        Position3: "92",
        Player3Fname: "A.J.",
        Player3Lname: "BOUYE",
        Player3OVR: 92
    },
    {
        TeamFname: "NEW ORLEANS",
        TeamLname: "SAINTS",
        TeamPic: "/SAINTS.png",
        TeamRating: 84,
        TeamOFF: 87,
        TeamDEF: 85,
        Position1: "QB",
        Player1Fname: "DREW",
        Player1Lname: "BREES",
        Player1OVR: 94,
        Position2: "LE",
        Player2Fname: "CAMERON",
        Player2Lname: "J0RDAN",
        Player2OVR: 94,
        Position3: "WR",
        Player3Fname: "MICHEAL",
        Player3Lname: "THOMAS",
        Player3OVR: 93
    },
    {
        TeamFname: "LOS ANGELES",
        TeamLname: "CHARGERS",
        TeamPic: "/CHARGERS.png",
        TeamRating: 80,
        TeamOFF: 83,
        TeamDEF: 83,
        Position1: "WR",
        Player1Fname: "KEENAN",
        Player1Lname: "ALLEN",
        Player1OVR: 91,
        Position2: "HB",
        Player2Fname: "MELVIN",
        Player2Lname: "GORDON III",
        Player2OVR: 91,
        Position3: "CB",
        Player3Fname: "CASEY",
        Player3Lname: "HAYWARD JR",
        Player3OVR: 91
    },
    {
        TeamFname: "PITTSBURGH",
        TeamLname: "STEELERS",
        TeamPic: "/STEELERS.png",
        TeamRating: 85,
        TeamOFF: 91,
        TeamDEF: 81,
        Position1: "WR",
        Player1Fname: "ANTONIO",
        Player1Lname: "BROWN",
        Player1OVR: 99,
        Position2: "HB",
        Player2Fname: "LE'VEON",
        Player2Lname: "BELL",
        Player2OVR: 96,
        Position3: "RG",
        Player3Fname: "DAVID",
        Player3Lname: "DECASTRO",
        Player3OVR: 95
    },
    {
        TeamFname: "LOS ANGELES",
        TeamLname: "RAMS",
        TeamPic: "/RAMS.png",
        TeamRating: 86,
        TeamOFF: 89,
        TeamDEF: 87,
        Position1: "RE",
        Player1Fname: "AARON",
        Player1Lname: "DONALD",
        Player1OVR: 99,
        Position2: "HB",
        Player2Fname: "TODD",
        Player2Lname: "GURLEY II",
        Player2OVR: 94,
        Position3: "DT",
        Player3Fname: "NDAMUKONG",
        Player3Lname: "SUH",
        Player3OVR: 94
    },
    {
        TeamFname: "PHILADELPHIA",
        TeamLname: "EAGLES",
        TeamPic: "/EAGLES.png",
        TeamRating: 91,
        TeamOFF: 97,
        TeamDEF: 89,
        Position1: "DT",
        Player1Fname: "FLETCHER",
        Player1Lname: "COX",
        Player1OVR: 94,
        Position2: "SS",
        Player2Fname: "MALCOLM",
        Player2Lname: "JENKINS",
        Player2OVR: 94,
        Position3: "LE",
        Player3Fname: "BRANDON",
        Player3Lname: "GRAHAM",
        Player3OVR: 93
    },
    {
        TeamFname: "NEW ENGLAND",
        TeamLname: "PATRIOTS",
        TeamPic: "/PATRIOTS.png",
        TeamRating: 85,
        TeamOFF: 89,
        TeamDEF: 87,
        Position1: "TE",
        Player1Fname: "ROB",
        Player1Lname: "GRONKOWSKI",
        Player1OVR: 99,
        Position2: "QB",
        Player2Fname: "TOM",
        Player2Lname: "BRADY",
        Player2OVR: 99,
        Position3: "FS",
        Player3Fname: "DEVIN",
        Player3Lname: "MCCOURTY",
        Player3OVR: 92
    },
    {
        TeamFname: "DALLAS",
        TeamLname: "COWBOYS",
        TeamPic: "/COWBOYS.jpeg",
        TeamRating: 84,
        TeamOFF: 89,
        TeamDEF: 83,
        Position1: "RG",
        Player1Fname: "ZACK",
        Player1Lname: "MARTIN",
        Player1OVR: 96,
        Position2: "C",
        Player2Fname: "TRAVIS",
        Player2Lname: "FREDERICK",
        Player2OVR: 95,
        Position3: "ROLB",
        Player3Fname: "SEAN",
        Player3Lname: "LEE",
        Player3OVR: 95
    }
];
